#!/bin/bash

FILENAME=""
VERBOSE=0
while getopts "vf:" OPTION
do
	case $OPTION in
		v)
			VERBOSE=1
			;;
		f)
			FILENAME=$OPTARG
            echo $OPTARG
			;;
		\?)
			echo "CS6501 Software Artifacts Music Analyzer"
            echo " "
            echo "music_analyzer [options] -f [file]"
            echo " "
            echo "Options"
            echo "=============================================="
            echo " "
            echo "-v     Prints all information about violations"
            echo " "
            echo "=============================================="
            exit
			;;
	esac
done

if [ "$FILENAME" == "" ]; then
    echo "Please Input .mscx file after the flag -f"
    echo " "
    echo "CS6501 Software Artifacts Music Analyzer"
    echo " "
    echo "music_analyzer [options] -f [file]"
    echo " "
    echo "Options"
    echo "========================================================"
    echo " "
    echo "-v               Prints all information about violations"
    echo " "
    echo "========================================================"
else
    python3 source/music_analyzer.py $FILENAME $VERBOSE
fi